// <auto-generated />
namespace WebSiteHome.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit2tablesiteUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit2tablesiteUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201908281127345_edit2 table siteUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
